name: shell commands
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name : string
        run: echo "Sanyasi workflow"
      - name : multiline script
        run: |
          mode -v
          npm -v
      - name: python-command
        run : |
          import platform
          print (platform.processor())
        shell: python      